#!/usr/bin/python
# Encoding: UTF-8
""" Check wether the device given as argument has a backup signature """

import os
import sys

if __name__ == "__main__":
    if len(sys.argv) == 2:
        signature = ""
        try:
            fd = os.open(sys.argv[1], os.O_RDONLY)
            os.lseek(fd, 440, 0)
            signature = os.read(fd, 4)
            os.close(fd)
        except:
            pass
        if signature == "BKUP":
            sys.exit(0)
    sys.exit(1)
